services:
  minecraft:
    image: eclipse-temurin:17-jre
    container_name: server_arclight
    ports:
      - "25565:25565"
    volumes:
      - ./:/data
    working_dir: /data
    command: java -Xms2G -Xmx4G -jar arclight.jar nogui
    stdin_open: true
    tty: true
    restart: unless-stopped